name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run release

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "deno-cljs"
          exclude: "node_modules"
          entrypoint: "./dist/api/api.js"